---
# tasks file for mariadb

- name: Installer MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Démarrer et activer MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
