---
# tasks file for apache
- name: Installer Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Démarrer et activer Apache
  service:
    name: apache2
    state: started
    enabled: yes

